// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/stt.proto

package sttpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Language              string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	SampleRate            uint32                 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	InitialPrompt         string                 `protobuf:"bytes,3,opt,name=initial_prompt,json=initialPrompt,proto3" json:"initial_prompt,omitempty"`
	Hotwords              string                 `protobuf:"bytes,4,opt,name=hotwords,proto3" json:"hotwords,omitempty"`
	Partials              bool                   `protobuf:"varint,5,opt,name=partials,proto3" json:"partials,omitempty"`
	PartialWindowMs       uint32                 `protobuf:"varint,6,opt,name=partial_window_ms,json=partialWindowMs,proto3" json:"partial_window_ms,omitempty"`
	PartialStrideMs       uint32                 `protobuf:"varint,7,opt,name=partial_stride_ms,json=partialStrideMs,proto3" json:"partial_stride_ms,omitempty"`
	IncludeWordTimestamps bool                   `protobuf:"varint,8,opt,name=include_word_timestamps,json=includeWordTimestamps,proto3" json:"include_word_timestamps,omitempty"`
	ModelId               string                 `protobuf:"bytes,9,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Task                  string                 `protobuf:"bytes,10,opt,name=task,proto3" json:"task,omitempty"`
	Temperature           float32                `protobuf:"fixed32,11,opt,name=temperature,proto3" json:"temperature,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SessionConfig) Reset() {
	*x = SessionConfig{}
	mi := &file_proto_stt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionConfig) ProtoMessage() {}

func (x *SessionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionConfig.ProtoReflect.Descriptor instead.
func (*SessionConfig) Descriptor() ([]byte, []int) {
	return file_proto_stt_proto_rawDescGZIP(), []int{0}
}

func (x *SessionConfig) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SessionConfig) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *SessionConfig) GetInitialPrompt() string {
	if x != nil {
		return x.InitialPrompt
	}
	return ""
}

func (x *SessionConfig) GetHotwords() string {
	if x != nil {
		return x.Hotwords
	}
	return ""
}

func (x *SessionConfig) GetPartials() bool {
	if x != nil {
		return x.Partials
	}
	return false
}

func (x *SessionConfig) GetPartialWindowMs() uint32 {
	if x != nil {
		return x.PartialWindowMs
	}
	return 0
}

func (x *SessionConfig) GetPartialStrideMs() uint32 {
	if x != nil {
		return x.PartialStrideMs
	}
	return 0
}

func (x *SessionConfig) GetIncludeWordTimestamps() bool {
	if x != nil {
		return x.IncludeWordTimestamps
	}
	return false
}

func (x *SessionConfig) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *SessionConfig) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *SessionConfig) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_proto_stt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_stt_proto_rawDescGZIP(), []int{1}
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*STTModel            `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_proto_stt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_stt_proto_rawDescGZIP(), []int{2}
}

func (x *ListModelsResponse) GetModels() []*STTModel {
	if x != nil {
		return x.Models
	}
	return nil
}

type STTModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *STTModel) Reset() {
	*x = STTModel{}
	mi := &file_proto_stt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *STTModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*STTModel) ProtoMessage() {}

func (x *STTModel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use STTModel.ProtoReflect.Descriptor instead.
func (*STTModel) Descriptor() ([]byte, []int) {
	return file_proto_stt_proto_rawDescGZIP(), []int{3}
}

func (x *STTModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *STTModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *STTModel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListLanguagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLanguagesRequest) Reset() {
	*x = ListLanguagesRequest{}
	mi := &file_proto_stt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLanguagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLanguagesRequest) ProtoMessage() {}

func (x *ListLanguagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLanguagesRequest.ProtoReflect.Descriptor instead.
func (*ListLanguagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_stt_proto_rawDescGZIP(), []int{4}
}

type ListLanguagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Languages     []string               `protobuf:"bytes,1,rep,name=languages,proto3" json:"languages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLanguagesResponse) Reset() {
	*x = ListLanguagesResponse{}
	mi := &file_proto_stt_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLanguagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLanguagesResponse) ProtoMessage() {}

func (x *ListLanguagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stt_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLanguagesResponse.ProtoReflect.Descriptor instead.
func (*ListLanguagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_stt_proto_rawDescGZIP(), []int{5}
}

func (x *ListLanguagesResponse) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

type AudioFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SampleRate    uint32                 `protobuf:"varint,1,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Pcm16         []byte                 `protobuf:"bytes,2,opt,name=pcm16,proto3" json:"pcm16,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioFrame) Reset() {
	*x = AudioFrame{}
	mi := &file_proto_stt_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioFrame) ProtoMessage() {}

func (x *AudioFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stt_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioFrame.ProtoReflect.Descriptor instead.
func (*AudioFrame) Descriptor() ([]byte, []int) {
	return file_proto_stt_proto_rawDescGZIP(), []int{6}
}

func (x *AudioFrame) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioFrame) GetPcm16() []byte {
	if x != nil {
		return x.Pcm16
	}
	return nil
}

type EncodedAudio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodedAudio) Reset() {
	*x = EncodedAudio{}
	mi := &file_proto_stt_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodedAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodedAudio) ProtoMessage() {}

func (x *EncodedAudio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stt_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodedAudio.ProtoReflect.Descriptor instead.
func (*EncodedAudio) Descriptor() ([]byte, []int) {
	return file_proto_stt_proto_rawDescGZIP(), []int{7}
}

func (x *EncodedAudio) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *EncodedAudio) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type OpusFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	SampleRate    uint32                 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Channels      uint32                 `protobuf:"varint,3,opt,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpusFrame) Reset() {
	*x = OpusFrame{}
	mi := &file_proto_stt_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpusFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpusFrame) ProtoMessage() {}

func (x *OpusFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stt_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpusFrame.ProtoReflect.Descriptor instead.
func (*OpusFrame) Descriptor() ([]byte, []int) {
	return file_proto_stt_proto_rawDescGZIP(), []int{8}
}

func (x *OpusFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OpusFrame) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *OpusFrame) GetChannels() uint32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

type ReadyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyMessage) Reset() {
	*x = ReadyMessage{}
	mi := &file_proto_stt_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyMessage) ProtoMessage() {}

func (x *ReadyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stt_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyMessage.ProtoReflect.Descriptor instead.
func (*ReadyMessage) Descriptor() ([]byte, []int) {
	return file_proto_stt_proto_rawDescGZIP(), []int{9}
}

type SpeechStartedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeechStartedMessage) Reset() {
	*x = SpeechStartedMessage{}
	mi := &file_proto_stt_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeechStartedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeechStartedMessage) ProtoMessage() {}

func (x *SpeechStartedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stt_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeechStartedMessage.ProtoReflect.Descriptor instead.
func (*SpeechStartedMessage) Descriptor() ([]byte, []int) {
	return file_proto_stt_proto_rawDescGZIP(), []int{10}
}

type SpeechStoppedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeechStoppedMessage) Reset() {
	*x = SpeechStoppedMessage{}
	mi := &file_proto_stt_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeechStoppedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeechStoppedMessage) ProtoMessage() {}

func (x *SpeechStoppedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stt_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeechStoppedMessage.ProtoReflect.Descriptor instead.
func (*SpeechStoppedMessage) Descriptor() ([]byte, []int) {
	return file_proto_stt_proto_rawDescGZIP(), []int{11}
}

type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_proto_stt_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stt_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_proto_stt_proto_rawDescGZIP(), []int{12}
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Segment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Start         float32                `protobuf:"fixed32,2,opt,name=start,proto3" json:"start,omitempty"`
	End           float32                `protobuf:"fixed32,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_proto_stt_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stt_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_proto_stt_proto_rawDescGZIP(), []int{13}
}

func (x *Segment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Segment) GetStart() float32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Segment) GetEnd() float32 {
	if x != nil {
		return x.End
	}
	return 0
}

type Usage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   uint64                 `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  uint64                 `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_proto_stt_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stt_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_proto_stt_proto_rawDescGZIP(), []int{14}
}

func (x *Usage) GetInputTokens() uint64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() uint64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

type TranscriptWord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Start         float32                `protobuf:"fixed32,2,opt,name=start,proto3" json:"start,omitempty"`
	End           float32                `protobuf:"fixed32,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptWord) Reset() {
	*x = TranscriptWord{}
	mi := &file_proto_stt_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptWord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptWord) ProtoMessage() {}

func (x *TranscriptWord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stt_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptWord.ProtoReflect.Descriptor instead.
func (*TranscriptWord) Descriptor() ([]byte, []int) {
	return file_proto_stt_proto_rawDescGZIP(), []int{15}
}

func (x *TranscriptWord) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *TranscriptWord) GetStart() float32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TranscriptWord) GetEnd() float32 {
	if x != nil {
		return x.End
	}
	return 0
}

type TranscriptResult struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Text                 string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	IsPartial            bool                   `protobuf:"varint,2,opt,name=is_partial,json=isPartial,proto3" json:"is_partial,omitempty"`
	StartMs              uint64                 `protobuf:"varint,3,opt,name=start_ms,json=startMs,proto3" json:"start_ms,omitempty"`
	EndMs                uint64                 `protobuf:"varint,4,opt,name=end_ms,json=endMs,proto3" json:"end_ms,omitempty"`
	AudioDurationMs      uint64                 `protobuf:"varint,5,opt,name=audio_duration_ms,json=audioDurationMs,proto3" json:"audio_duration_ms,omitempty"`
	ProcessingDurationMs uint64                 `protobuf:"varint,6,opt,name=processing_duration_ms,json=processingDurationMs,proto3" json:"processing_duration_ms,omitempty"`
	Segments             []*Segment             `protobuf:"bytes,7,rep,name=segments,proto3" json:"segments,omitempty"`
	Usage                *Usage                 `protobuf:"bytes,8,opt,name=usage,proto3" json:"usage,omitempty"`
	Model                string                 `protobuf:"bytes,9,opt,name=model,proto3" json:"model,omitempty"`
	Words                []*TranscriptWord      `protobuf:"bytes,10,rep,name=words,proto3" json:"words,omitempty"`
	EouProbability       *float32               `protobuf:"fixed32,11,opt,name=eou_probability,json=eouProbability,proto3,oneof" json:"eou_probability,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TranscriptResult) Reset() {
	*x = TranscriptResult{}
	mi := &file_proto_stt_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptResult) ProtoMessage() {}

func (x *TranscriptResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stt_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptResult.ProtoReflect.Descriptor instead.
func (*TranscriptResult) Descriptor() ([]byte, []int) {
	return file_proto_stt_proto_rawDescGZIP(), []int{16}
}

func (x *TranscriptResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscriptResult) GetIsPartial() bool {
	if x != nil {
		return x.IsPartial
	}
	return false
}

func (x *TranscriptResult) GetStartMs() uint64 {
	if x != nil {
		return x.StartMs
	}
	return 0
}

func (x *TranscriptResult) GetEndMs() uint64 {
	if x != nil {
		return x.EndMs
	}
	return 0
}

func (x *TranscriptResult) GetAudioDurationMs() uint64 {
	if x != nil {
		return x.AudioDurationMs
	}
	return 0
}

func (x *TranscriptResult) GetProcessingDurationMs() uint64 {
	if x != nil {
		return x.ProcessingDurationMs
	}
	return 0
}

func (x *TranscriptResult) GetSegments() []*Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *TranscriptResult) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *TranscriptResult) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *TranscriptResult) GetWords() []*TranscriptWord {
	if x != nil {
		return x.Words
	}
	return nil
}

func (x *TranscriptResult) GetEouProbability() float32 {
	if x != nil && x.EouProbability != nil {
		return *x.EouProbability
	}
	return 0
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ClientMessage_Config
	//	*ClientMessage_Audio
	//	*ClientMessage_EncodedAudio
	//	*ClientMessage_EndOfStream
	//	*ClientMessage_OpusFrame
	Msg           isClientMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_proto_stt_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stt_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_proto_stt_proto_rawDescGZIP(), []int{17}
}

func (x *ClientMessage) GetMsg() isClientMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ClientMessage) GetConfig() *SessionConfig {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *ClientMessage) GetAudio() *AudioFrame {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *ClientMessage) GetEncodedAudio() *EncodedAudio {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_EncodedAudio); ok {
			return x.EncodedAudio
		}
	}
	return nil
}

func (x *ClientMessage) GetEndOfStream() bool {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_EndOfStream); ok {
			return x.EndOfStream
		}
	}
	return false
}

func (x *ClientMessage) GetOpusFrame() *OpusFrame {
	if x != nil {
		if x, ok := x.Msg.(*ClientMessage_OpusFrame); ok {
			return x.OpusFrame
		}
	}
	return nil
}

type isClientMessage_Msg interface {
	isClientMessage_Msg()
}

type ClientMessage_Config struct {
	Config *SessionConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type ClientMessage_Audio struct {
	Audio *AudioFrame `protobuf:"bytes,2,opt,name=audio,proto3,oneof"`
}

type ClientMessage_EncodedAudio struct {
	EncodedAudio *EncodedAudio `protobuf:"bytes,3,opt,name=encoded_audio,json=encodedAudio,proto3,oneof"`
}

type ClientMessage_EndOfStream struct {
	EndOfStream bool `protobuf:"varint,4,opt,name=end_of_stream,json=endOfStream,proto3,oneof"`
}

type ClientMessage_OpusFrame struct {
	OpusFrame *OpusFrame `protobuf:"bytes,5,opt,name=opus_frame,json=opusFrame,proto3,oneof"`
}

func (*ClientMessage_Config) isClientMessage_Msg() {}

func (*ClientMessage_Audio) isClientMessage_Msg() {}

func (*ClientMessage_EncodedAudio) isClientMessage_Msg() {}

func (*ClientMessage_EndOfStream) isClientMessage_Msg() {}

func (*ClientMessage_OpusFrame) isClientMessage_Msg() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMessage_Ready
	//	*ServerMessage_SpeechStarted
	//	*ServerMessage_SpeechStopped
	//	*ServerMessage_Transcript
	//	*ServerMessage_Error
	Msg           isServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_stt_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stt_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_stt_proto_rawDescGZIP(), []int{18}
}

func (x *ServerMessage) GetMsg() isServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMessage) GetReady() *ReadyMessage {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *ServerMessage) GetSpeechStarted() *SpeechStartedMessage {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_SpeechStarted); ok {
			return x.SpeechStarted
		}
	}
	return nil
}

func (x *ServerMessage) GetSpeechStopped() *SpeechStoppedMessage {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_SpeechStopped); ok {
			return x.SpeechStopped
		}
	}
	return nil
}

func (x *ServerMessage) GetTranscript() *TranscriptResult {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Transcript); ok {
			return x.Transcript
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *ErrorMessage {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_Ready struct {
	Ready *ReadyMessage `protobuf:"bytes,1,opt,name=ready,proto3,oneof"`
}

type ServerMessage_SpeechStarted struct {
	SpeechStarted *SpeechStartedMessage `protobuf:"bytes,2,opt,name=speech_started,json=speechStarted,proto3,oneof"`
}

type ServerMessage_SpeechStopped struct {
	SpeechStopped *SpeechStoppedMessage `protobuf:"bytes,3,opt,name=speech_stopped,json=speechStopped,proto3,oneof"`
}

type ServerMessage_Transcript struct {
	Transcript *TranscriptResult `protobuf:"bytes,4,opt,name=transcript,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *ErrorMessage `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*ServerMessage_Ready) isServerMessage_Msg() {}

func (*ServerMessage_SpeechStarted) isServerMessage_Msg() {}

func (*ServerMessage_SpeechStopped) isServerMessage_Msg() {}

func (*ServerMessage_Transcript) isServerMessage_Msg() {}

func (*ServerMessage_Error) isServerMessage_Msg() {}

var File_proto_stt_proto protoreflect.FileDescriptor

const file_proto_stt_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/stt.proto\x12\x03stt\"\x8c\x03\n" +
	"\rSessionConfig\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\rR\n" +
	"sampleRate\x12%\n" +
	"\x0einitial_prompt\x18\x03 \x01(\tR\rinitialPrompt\x12\x1a\n" +
	"\bhotwords\x18\x04 \x01(\tR\bhotwords\x12\x1a\n" +
	"\bpartials\x18\x05 \x01(\bR\bpartials\x12*\n" +
	"\x11partial_window_ms\x18\x06 \x01(\rR\x0fpartialWindowMs\x12*\n" +
	"\x11partial_stride_ms\x18\a \x01(\rR\x0fpartialStrideMs\x126\n" +
	"\x17include_word_timestamps\x18\b \x01(\bR\x15includeWordTimestamps\x12\x19\n" +
	"\bmodel_id\x18\t \x01(\tR\amodelId\x12\x12\n" +
	"\x04task\x18\n" +
	" \x01(\tR\x04task\x12 \n" +
	"\vtemperature\x18\v \x01(\x02R\vtemperature\"\x13\n" +
	"\x11ListModelsRequest\";\n" +
	"\x12ListModelsResponse\x12%\n" +
	"\x06models\x18\x01 \x03(\v2\r.stt.STTModelR\x06models\"P\n" +
	"\bSTTModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x16\n" +
	"\x14ListLanguagesRequest\"5\n" +
	"\x15ListLanguagesResponse\x12\x1c\n" +
	"\tlanguages\x18\x01 \x03(\tR\tlanguages\"C\n" +
	"\n" +
	"AudioFrame\x12\x1f\n" +
	"\vsample_rate\x18\x01 \x01(\rR\n" +
	"sampleRate\x12\x14\n" +
	"\x05pcm16\x18\x02 \x01(\fR\x05pcm16\":\n" +
	"\fEncodedAudio\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\\\n" +
	"\tOpusFrame\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\rR\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x03 \x01(\rR\bchannels\"\x0e\n" +
	"\fReadyMessage\"\x16\n" +
	"\x14SpeechStartedMessage\"\x16\n" +
	"\x14SpeechStoppedMessage\"(\n" +
	"\fErrorMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"E\n" +
	"\aSegment\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x02R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x02R\x03end\"O\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x04R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x04R\foutputTokens\"L\n" +
	"\x0eTranscriptWord\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x02R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x02R\x03end\"\xa8\x03\n" +
	"\x10TranscriptResult\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"is_partial\x18\x02 \x01(\bR\tisPartial\x12\x19\n" +
	"\bstart_ms\x18\x03 \x01(\x04R\astartMs\x12\x15\n" +
	"\x06end_ms\x18\x04 \x01(\x04R\x05endMs\x12*\n" +
	"\x11audio_duration_ms\x18\x05 \x01(\x04R\x0faudioDurationMs\x124\n" +
	"\x16processing_duration_ms\x18\x06 \x01(\x04R\x14processingDurationMs\x12(\n" +
	"\bsegments\x18\a \x03(\v2\f.stt.SegmentR\bsegments\x12 \n" +
	"\x05usage\x18\b \x01(\v2\n" +
	".stt.UsageR\x05usage\x12\x14\n" +
	"\x05model\x18\t \x01(\tR\x05model\x12)\n" +
	"\x05words\x18\n" +
	" \x03(\v2\x13.stt.TranscriptWordR\x05words\x12,\n" +
	"\x0feou_probability\x18\v \x01(\x02H\x00R\x0eeouProbability\x88\x01\x01B\x12\n" +
	"\x10_eou_probability\"\xfe\x01\n" +
	"\rClientMessage\x12,\n" +
	"\x06config\x18\x01 \x01(\v2\x12.stt.SessionConfigH\x00R\x06config\x12'\n" +
	"\x05audio\x18\x02 \x01(\v2\x0f.stt.AudioFrameH\x00R\x05audio\x128\n" +
	"\rencoded_audio\x18\x03 \x01(\v2\x11.stt.EncodedAudioH\x00R\fencodedAudio\x12$\n" +
	"\rend_of_stream\x18\x04 \x01(\bH\x00R\vendOfStream\x12/\n" +
	"\n" +
	"opus_frame\x18\x05 \x01(\v2\x0e.stt.OpusFrameH\x00R\topusFrameB\x05\n" +
	"\x03msg\"\xad\x02\n" +
	"\rServerMessage\x12)\n" +
	"\x05ready\x18\x01 \x01(\v2\x11.stt.ReadyMessageH\x00R\x05ready\x12B\n" +
	"\x0espeech_started\x18\x02 \x01(\v2\x19.stt.SpeechStartedMessageH\x00R\rspeechStarted\x12B\n" +
	"\x0espeech_stopped\x18\x03 \x01(\v2\x19.stt.SpeechStoppedMessageH\x00R\rspeechStopped\x127\n" +
	"\n" +
	"transcript\x18\x04 \x01(\v2\x15.stt.TranscriptResultH\x00R\n" +
	"transcript\x12)\n" +
	"\x05error\x18\x05 \x01(\v2\x11.stt.ErrorMessageH\x00R\x05errorB\x05\n" +
	"\x03msg2\xd7\x01\n" +
	"\x14TranscriptionService\x128\n" +
	"\n" +
	"Transcribe\x12\x12.stt.ClientMessage\x1a\x12.stt.ServerMessage(\x010\x01\x12=\n" +
	"\n" +
	"ListModels\x12\x16.stt.ListModelsRequest\x1a\x17.stt.ListModelsResponse\x12F\n" +
	"\rListLanguages\x12\x19.stt.ListLanguagesRequest\x1a\x1a.stt.ListLanguagesResponseBAZ?github.com/eleven-am/voice-backend/internal/transcription/sttpbb\x06proto3"

var (
	file_proto_stt_proto_rawDescOnce sync.Once
	file_proto_stt_proto_rawDescData []byte
)

func file_proto_stt_proto_rawDescGZIP() []byte {
	file_proto_stt_proto_rawDescOnce.Do(func() {
		file_proto_stt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stt_proto_rawDesc), len(file_proto_stt_proto_rawDesc)))
	})
	return file_proto_stt_proto_rawDescData
}

var file_proto_stt_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_stt_proto_goTypes = []any{
	(*SessionConfig)(nil),         // 0: stt.SessionConfig
	(*ListModelsRequest)(nil),     // 1: stt.ListModelsRequest
	(*ListModelsResponse)(nil),    // 2: stt.ListModelsResponse
	(*STTModel)(nil),              // 3: stt.STTModel
	(*ListLanguagesRequest)(nil),  // 4: stt.ListLanguagesRequest
	(*ListLanguagesResponse)(nil), // 5: stt.ListLanguagesResponse
	(*AudioFrame)(nil),            // 6: stt.AudioFrame
	(*EncodedAudio)(nil),          // 7: stt.EncodedAudio
	(*OpusFrame)(nil),             // 8: stt.OpusFrame
	(*ReadyMessage)(nil),          // 9: stt.ReadyMessage
	(*SpeechStartedMessage)(nil),  // 10: stt.SpeechStartedMessage
	(*SpeechStoppedMessage)(nil),  // 11: stt.SpeechStoppedMessage
	(*ErrorMessage)(nil),          // 12: stt.ErrorMessage
	(*Segment)(nil),               // 13: stt.Segment
	(*Usage)(nil),                 // 14: stt.Usage
	(*TranscriptWord)(nil),        // 15: stt.TranscriptWord
	(*TranscriptResult)(nil),      // 16: stt.TranscriptResult
	(*ClientMessage)(nil),         // 17: stt.ClientMessage
	(*ServerMessage)(nil),         // 18: stt.ServerMessage
}
var file_proto_stt_proto_depIdxs = []int32{
	3,  // 0: stt.ListModelsResponse.models:type_name -> stt.STTModel
	13, // 1: stt.TranscriptResult.segments:type_name -> stt.Segment
	14, // 2: stt.TranscriptResult.usage:type_name -> stt.Usage
	15, // 3: stt.TranscriptResult.words:type_name -> stt.TranscriptWord
	0,  // 4: stt.ClientMessage.config:type_name -> stt.SessionConfig
	6,  // 5: stt.ClientMessage.audio:type_name -> stt.AudioFrame
	7,  // 6: stt.ClientMessage.encoded_audio:type_name -> stt.EncodedAudio
	8,  // 7: stt.ClientMessage.opus_frame:type_name -> stt.OpusFrame
	9,  // 8: stt.ServerMessage.ready:type_name -> stt.ReadyMessage
	10, // 9: stt.ServerMessage.speech_started:type_name -> stt.SpeechStartedMessage
	11, // 10: stt.ServerMessage.speech_stopped:type_name -> stt.SpeechStoppedMessage
	16, // 11: stt.ServerMessage.transcript:type_name -> stt.TranscriptResult
	12, // 12: stt.ServerMessage.error:type_name -> stt.ErrorMessage
	17, // 13: stt.TranscriptionService.Transcribe:input_type -> stt.ClientMessage
	1,  // 14: stt.TranscriptionService.ListModels:input_type -> stt.ListModelsRequest
	4,  // 15: stt.TranscriptionService.ListLanguages:input_type -> stt.ListLanguagesRequest
	18, // 16: stt.TranscriptionService.Transcribe:output_type -> stt.ServerMessage
	2,  // 17: stt.TranscriptionService.ListModels:output_type -> stt.ListModelsResponse
	5,  // 18: stt.TranscriptionService.ListLanguages:output_type -> stt.ListLanguagesResponse
	16, // [16:19] is the sub-list for method output_type
	13, // [13:16] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_stt_proto_init() }
func file_proto_stt_proto_init() {
	if File_proto_stt_proto != nil {
		return
	}
	file_proto_stt_proto_msgTypes[16].OneofWrappers = []any{}
	file_proto_stt_proto_msgTypes[17].OneofWrappers = []any{
		(*ClientMessage_Config)(nil),
		(*ClientMessage_Audio)(nil),
		(*ClientMessage_EncodedAudio)(nil),
		(*ClientMessage_EndOfStream)(nil),
		(*ClientMessage_OpusFrame)(nil),
	}
	file_proto_stt_proto_msgTypes[18].OneofWrappers = []any{
		(*ServerMessage_Ready)(nil),
		(*ServerMessage_SpeechStarted)(nil),
		(*ServerMessage_SpeechStopped)(nil),
		(*ServerMessage_Transcript)(nil),
		(*ServerMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stt_proto_rawDesc), len(file_proto_stt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stt_proto_goTypes,
		DependencyIndexes: file_proto_stt_proto_depIdxs,
		MessageInfos:      file_proto_stt_proto_msgTypes,
	}.Build()
	File_proto_stt_proto = out.File
	file_proto_stt_proto_goTypes = nil
	file_proto_stt_proto_depIdxs = nil
}
