// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/stt.proto

package sttpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TranscriptionService_Transcribe_FullMethodName    = "/stt.TranscriptionService/Transcribe"
	TranscriptionService_ListModels_FullMethodName    = "/stt.TranscriptionService/ListModels"
	TranscriptionService_ListLanguages_FullMethodName = "/stt.TranscriptionService/ListLanguages"
)

// TranscriptionServiceClient is the client API for TranscriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TranscriptionServiceClient interface {
	Transcribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	ListLanguages(ctx context.Context, in *ListLanguagesRequest, opts ...grpc.CallOption) (*ListLanguagesResponse, error)
}

type transcriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranscriptionServiceClient(cc grpc.ClientConnInterface) TranscriptionServiceClient {
	return &transcriptionServiceClient{cc}
}

func (c *transcriptionServiceClient) Transcribe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TranscriptionService_ServiceDesc.Streams[0], TranscriptionService_Transcribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranscriptionService_TranscribeClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

func (c *transcriptionServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, TranscriptionService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcriptionServiceClient) ListLanguages(ctx context.Context, in *ListLanguagesRequest, opts ...grpc.CallOption) (*ListLanguagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLanguagesResponse)
	err := c.cc.Invoke(ctx, TranscriptionService_ListLanguages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TranscriptionServiceServer is the server API for TranscriptionService service.
// All implementations must embed UnimplementedTranscriptionServiceServer
// for forward compatibility.
type TranscriptionServiceServer interface {
	Transcribe(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	ListLanguages(context.Context, *ListLanguagesRequest) (*ListLanguagesResponse, error)
	mustEmbedUnimplementedTranscriptionServiceServer()
}

// UnimplementedTranscriptionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranscriptionServiceServer struct{}

func (UnimplementedTranscriptionServiceServer) Transcribe(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Transcribe not implemented")
}
func (UnimplementedTranscriptionServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedTranscriptionServiceServer) ListLanguages(context.Context, *ListLanguagesRequest) (*ListLanguagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLanguages not implemented")
}
func (UnimplementedTranscriptionServiceServer) mustEmbedUnimplementedTranscriptionServiceServer() {}
func (UnimplementedTranscriptionServiceServer) testEmbeddedByValue()                              {}

// UnsafeTranscriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranscriptionServiceServer will
// result in compilation errors.
type UnsafeTranscriptionServiceServer interface {
	mustEmbedUnimplementedTranscriptionServiceServer()
}

func RegisterTranscriptionServiceServer(s grpc.ServiceRegistrar, srv TranscriptionServiceServer) {
	// If the following call panics, it indicates UnimplementedTranscriptionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TranscriptionService_ServiceDesc, srv)
}

func _TranscriptionService_Transcribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TranscriptionServiceServer).Transcribe(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranscriptionService_TranscribeServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

func _TranscriptionService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscriptionServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscriptionService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscriptionServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscriptionService_ListLanguages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLanguagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscriptionServiceServer).ListLanguages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscriptionService_ListLanguages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscriptionServiceServer).ListLanguages(ctx, req.(*ListLanguagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TranscriptionService_ServiceDesc is the grpc.ServiceDesc for TranscriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranscriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stt.TranscriptionService",
	HandlerType: (*TranscriptionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListModels",
			Handler:    _TranscriptionService_ListModels_Handler,
		},
		{
			MethodName: "ListLanguages",
			Handler:    _TranscriptionService_ListLanguages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transcribe",
			Handler:       _TranscriptionService_Transcribe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/stt.proto",
}
