// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/tts.proto

package ttspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TtsSessionConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VoiceId        string                 `protobuf:"bytes,1,opt,name=voice_id,json=voiceId,proto3" json:"voice_id,omitempty"`
	SampleRate     uint32                 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Speed          float32                `protobuf:"fixed32,3,opt,name=speed,proto3" json:"speed,omitempty"`
	ModelId        string                 `protobuf:"bytes,4,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Instructions   string                 `protobuf:"bytes,5,opt,name=instructions,proto3" json:"instructions,omitempty"`
	Language       string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	ResponseFormat string                 `protobuf:"bytes,7,opt,name=response_format,json=responseFormat,proto3" json:"response_format,omitempty"` // pcm, opus, mp3 (streaming) | wav, flac (batch)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TtsSessionConfig) Reset() {
	*x = TtsSessionConfig{}
	mi := &file_proto_tts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtsSessionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtsSessionConfig) ProtoMessage() {}

func (x *TtsSessionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtsSessionConfig.ProtoReflect.Descriptor instead.
func (*TtsSessionConfig) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{0}
}

func (x *TtsSessionConfig) GetVoiceId() string {
	if x != nil {
		return x.VoiceId
	}
	return ""
}

func (x *TtsSessionConfig) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *TtsSessionConfig) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *TtsSessionConfig) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *TtsSessionConfig) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *TtsSessionConfig) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *TtsSessionConfig) GetResponseFormat() string {
	if x != nil {
		return x.ResponseFormat
	}
	return ""
}

type ListVoicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVoicesRequest) Reset() {
	*x = ListVoicesRequest{}
	mi := &file_proto_tts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVoicesRequest) ProtoMessage() {}

func (x *ListVoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVoicesRequest.ProtoReflect.Descriptor instead.
func (*ListVoicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{1}
}

type ListVoicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voices        []*Voice               `protobuf:"bytes,1,rep,name=voices,proto3" json:"voices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVoicesResponse) Reset() {
	*x = ListVoicesResponse{}
	mi := &file_proto_tts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVoicesResponse) ProtoMessage() {}

func (x *ListVoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVoicesResponse.ProtoReflect.Descriptor instead.
func (*ListVoicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{2}
}

func (x *ListVoicesResponse) GetVoices() []*Voice {
	if x != nil {
		return x.Voices
	}
	return nil
}

type Voice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Voice) Reset() {
	*x = Voice{}
	mi := &file_proto_tts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Voice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Voice) ProtoMessage() {}

func (x *Voice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Voice.ProtoReflect.Descriptor instead.
func (*Voice) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{3}
}

func (x *Voice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Voice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Voice) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Voice) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type CreateVoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoiceId       string                 `protobuf:"bytes,1,opt,name=voice_id,json=voiceId,proto3" json:"voice_id,omitempty"`
	AudioData     []byte                 `protobuf:"bytes,2,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	ReferenceText string                 `protobuf:"bytes,6,opt,name=reference_text,json=referenceText,proto3" json:"reference_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVoiceRequest) Reset() {
	*x = CreateVoiceRequest{}
	mi := &file_proto_tts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVoiceRequest) ProtoMessage() {}

func (x *CreateVoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVoiceRequest.ProtoReflect.Descriptor instead.
func (*CreateVoiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{4}
}

func (x *CreateVoiceRequest) GetVoiceId() string {
	if x != nil {
		return x.VoiceId
	}
	return ""
}

func (x *CreateVoiceRequest) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *CreateVoiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVoiceRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CreateVoiceRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateVoiceRequest) GetReferenceText() string {
	if x != nil {
		return x.ReferenceText
	}
	return ""
}

type CreateVoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voice         *Voice                 `protobuf:"bytes,1,opt,name=voice,proto3" json:"voice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVoiceResponse) Reset() {
	*x = CreateVoiceResponse{}
	mi := &file_proto_tts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVoiceResponse) ProtoMessage() {}

func (x *CreateVoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVoiceResponse.ProtoReflect.Descriptor instead.
func (*CreateVoiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{5}
}

func (x *CreateVoiceResponse) GetVoice() *Voice {
	if x != nil {
		return x.Voice
	}
	return nil
}

type DeleteVoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoiceId       string                 `protobuf:"bytes,1,opt,name=voice_id,json=voiceId,proto3" json:"voice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVoiceRequest) Reset() {
	*x = DeleteVoiceRequest{}
	mi := &file_proto_tts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVoiceRequest) ProtoMessage() {}

func (x *DeleteVoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVoiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteVoiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteVoiceRequest) GetVoiceId() string {
	if x != nil {
		return x.VoiceId
	}
	return ""
}

type DeleteVoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVoiceResponse) Reset() {
	*x = DeleteVoiceResponse{}
	mi := &file_proto_tts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVoiceResponse) ProtoMessage() {}

func (x *DeleteVoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVoiceResponse.ProtoReflect.Descriptor instead.
func (*DeleteVoiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteVoiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_proto_tts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{8}
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*TTSModel            `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_proto_tts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{9}
}

func (x *ListModelsResponse) GetModels() []*TTSModel {
	if x != nil {
		return x.Models
	}
	return nil
}

type TTSModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTSModel) Reset() {
	*x = TTSModel{}
	mi := &file_proto_tts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTSModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTSModel) ProtoMessage() {}

func (x *TTSModel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTSModel.ProtoReflect.Descriptor instead.
func (*TTSModel) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{10}
}

func (x *TTSModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TTSModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TTSModel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TextChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextChunk) Reset() {
	*x = TextChunk{}
	mi := &file_proto_tts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextChunk) ProtoMessage() {}

func (x *TextChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextChunk.ProtoReflect.Descriptor instead.
func (*TextChunk) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{11}
}

func (x *TextChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EndOfText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndOfText) Reset() {
	*x = EndOfText{}
	mi := &file_proto_tts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndOfText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndOfText) ProtoMessage() {}

func (x *EndOfText) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndOfText.ProtoReflect.Descriptor instead.
func (*EndOfText) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{12}
}

type TtsClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*TtsClientMessage_Config
	//	*TtsClientMessage_Text
	//	*TtsClientMessage_End
	Msg           isTtsClientMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TtsClientMessage) Reset() {
	*x = TtsClientMessage{}
	mi := &file_proto_tts_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtsClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtsClientMessage) ProtoMessage() {}

func (x *TtsClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtsClientMessage.ProtoReflect.Descriptor instead.
func (*TtsClientMessage) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{13}
}

func (x *TtsClientMessage) GetMsg() isTtsClientMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *TtsClientMessage) GetConfig() *TtsSessionConfig {
	if x != nil {
		if x, ok := x.Msg.(*TtsClientMessage_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *TtsClientMessage) GetText() *TextChunk {
	if x != nil {
		if x, ok := x.Msg.(*TtsClientMessage_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *TtsClientMessage) GetEnd() *EndOfText {
	if x != nil {
		if x, ok := x.Msg.(*TtsClientMessage_End); ok {
			return x.End
		}
	}
	return nil
}

type isTtsClientMessage_Msg interface {
	isTtsClientMessage_Msg()
}

type TtsClientMessage_Config struct {
	Config *TtsSessionConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type TtsClientMessage_Text struct {
	Text *TextChunk `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type TtsClientMessage_End struct {
	End *EndOfText `protobuf:"bytes,3,opt,name=end,proto3,oneof"`
}

func (*TtsClientMessage_Config) isTtsClientMessage_Msg() {}

func (*TtsClientMessage_Text) isTtsClientMessage_Msg() {}

func (*TtsClientMessage_End) isTtsClientMessage_Msg() {}

type TtsSessionReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoiceId       string                 `protobuf:"bytes,1,opt,name=voice_id,json=voiceId,proto3" json:"voice_id,omitempty"`
	SampleRate    uint32                 `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TtsSessionReady) Reset() {
	*x = TtsSessionReady{}
	mi := &file_proto_tts_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtsSessionReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtsSessionReady) ProtoMessage() {}

func (x *TtsSessionReady) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtsSessionReady.ProtoReflect.Descriptor instead.
func (*TtsSessionReady) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{14}
}

func (x *TtsSessionReady) GetVoiceId() string {
	if x != nil {
		return x.VoiceId
	}
	return ""
}

func (x *TtsSessionReady) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	SampleRate    uint32                 `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	TimestampMs   uint64                 `protobuf:"varint,4,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Transcript    string                 `protobuf:"bytes,5,opt,name=transcript,proto3" json:"transcript,omitempty"` // NEW: optional transcript text for this chunk
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_proto_tts_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{15}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunk) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *AudioChunk) GetSampleRate() uint32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioChunk) GetTimestampMs() uint64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *AudioChunk) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

type TtsUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioMs       uint64                 `protobuf:"varint,1,opt,name=audio_ms,json=audioMs,proto3" json:"audio_ms,omitempty"`
	ProcessingMs  uint64                 `protobuf:"varint,2,opt,name=processing_ms,json=processingMs,proto3" json:"processing_ms,omitempty"`
	TextChars     uint64                 `protobuf:"varint,3,opt,name=text_chars,json=textChars,proto3" json:"text_chars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TtsUsage) Reset() {
	*x = TtsUsage{}
	mi := &file_proto_tts_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtsUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtsUsage) ProtoMessage() {}

func (x *TtsUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtsUsage.ProtoReflect.Descriptor instead.
func (*TtsUsage) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{16}
}

func (x *TtsUsage) GetAudioMs() uint64 {
	if x != nil {
		return x.AudioMs
	}
	return 0
}

func (x *TtsUsage) GetProcessingMs() uint64 {
	if x != nil {
		return x.ProcessingMs
	}
	return 0
}

func (x *TtsUsage) GetTextChars() uint64 {
	if x != nil {
		return x.TextChars
	}
	return 0
}

type TtsDone struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AudioDurationMs      uint64                 `protobuf:"varint,1,opt,name=audio_duration_ms,json=audioDurationMs,proto3" json:"audio_duration_ms,omitempty"`
	ProcessingDurationMs uint64                 `protobuf:"varint,2,opt,name=processing_duration_ms,json=processingDurationMs,proto3" json:"processing_duration_ms,omitempty"`
	TextLength           uint64                 `protobuf:"varint,3,opt,name=text_length,json=textLength,proto3" json:"text_length,omitempty"`
	Usage                *TtsUsage              `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
	Transcript           string                 `protobuf:"bytes,5,opt,name=transcript,proto3" json:"transcript,omitempty"` // NEW: optional final transcript
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TtsDone) Reset() {
	*x = TtsDone{}
	mi := &file_proto_tts_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtsDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtsDone) ProtoMessage() {}

func (x *TtsDone) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtsDone.ProtoReflect.Descriptor instead.
func (*TtsDone) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{17}
}

func (x *TtsDone) GetAudioDurationMs() uint64 {
	if x != nil {
		return x.AudioDurationMs
	}
	return 0
}

func (x *TtsDone) GetProcessingDurationMs() uint64 {
	if x != nil {
		return x.ProcessingDurationMs
	}
	return 0
}

func (x *TtsDone) GetTextLength() uint64 {
	if x != nil {
		return x.TextLength
	}
	return 0
}

func (x *TtsDone) GetUsage() *TtsUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *TtsDone) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

type TtsError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          uint32                 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TtsError) Reset() {
	*x = TtsError{}
	mi := &file_proto_tts_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtsError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtsError) ProtoMessage() {}

func (x *TtsError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtsError.ProtoReflect.Descriptor instead.
func (*TtsError) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{18}
}

func (x *TtsError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TtsError) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type TtsServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*TtsServerMessage_Ready
	//	*TtsServerMessage_Audio
	//	*TtsServerMessage_Done
	//	*TtsServerMessage_Error
	Msg           isTtsServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TtsServerMessage) Reset() {
	*x = TtsServerMessage{}
	mi := &file_proto_tts_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtsServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtsServerMessage) ProtoMessage() {}

func (x *TtsServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tts_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtsServerMessage.ProtoReflect.Descriptor instead.
func (*TtsServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_tts_proto_rawDescGZIP(), []int{19}
}

func (x *TtsServerMessage) GetMsg() isTtsServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *TtsServerMessage) GetReady() *TtsSessionReady {
	if x != nil {
		if x, ok := x.Msg.(*TtsServerMessage_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *TtsServerMessage) GetAudio() *AudioChunk {
	if x != nil {
		if x, ok := x.Msg.(*TtsServerMessage_Audio); ok {
			return x.Audio
		}
	}
	return nil
}

func (x *TtsServerMessage) GetDone() *TtsDone {
	if x != nil {
		if x, ok := x.Msg.(*TtsServerMessage_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *TtsServerMessage) GetError() *TtsError {
	if x != nil {
		if x, ok := x.Msg.(*TtsServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isTtsServerMessage_Msg interface {
	isTtsServerMessage_Msg()
}

type TtsServerMessage_Ready struct {
	Ready *TtsSessionReady `protobuf:"bytes,1,opt,name=ready,proto3,oneof"`
}

type TtsServerMessage_Audio struct {
	Audio *AudioChunk `protobuf:"bytes,2,opt,name=audio,proto3,oneof"`
}

type TtsServerMessage_Done struct {
	Done *TtsDone `protobuf:"bytes,3,opt,name=done,proto3,oneof"`
}

type TtsServerMessage_Error struct {
	Error *TtsError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*TtsServerMessage_Ready) isTtsServerMessage_Msg() {}

func (*TtsServerMessage_Audio) isTtsServerMessage_Msg() {}

func (*TtsServerMessage_Done) isTtsServerMessage_Msg() {}

func (*TtsServerMessage_Error) isTtsServerMessage_Msg() {}

var File_proto_tts_proto protoreflect.FileDescriptor

const file_proto_tts_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/tts.proto\x12\x03tts\"\xe8\x01\n" +
	"\x10TtsSessionConfig\x12\x19\n" +
	"\bvoice_id\x18\x01 \x01(\tR\avoiceId\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\rR\n" +
	"sampleRate\x12\x14\n" +
	"\x05speed\x18\x03 \x01(\x02R\x05speed\x12\x19\n" +
	"\bmodel_id\x18\x04 \x01(\tR\amodelId\x12\"\n" +
	"\finstructions\x18\x05 \x01(\tR\finstructions\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12'\n" +
	"\x0fresponse_format\x18\a \x01(\tR\x0eresponseFormat\"\x13\n" +
	"\x11ListVoicesRequest\"8\n" +
	"\x12ListVoicesResponse\x12\"\n" +
	"\x06voices\x18\x01 \x03(\v2\n" +
	".tts.VoiceR\x06voices\"_\n" +
	"\x05Voice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\"\xbd\x01\n" +
	"\x12CreateVoiceRequest\x12\x19\n" +
	"\bvoice_id\x18\x01 \x01(\tR\avoiceId\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x02 \x01(\fR\taudioData\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12%\n" +
	"\x0ereference_text\x18\x06 \x01(\tR\rreferenceText\"7\n" +
	"\x13CreateVoiceResponse\x12 \n" +
	"\x05voice\x18\x01 \x01(\v2\n" +
	".tts.VoiceR\x05voice\"/\n" +
	"\x12DeleteVoiceRequest\x12\x19\n" +
	"\bvoice_id\x18\x01 \x01(\tR\avoiceId\"/\n" +
	"\x13DeleteVoiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x13\n" +
	"\x11ListModelsRequest\";\n" +
	"\x12ListModelsResponse\x12%\n" +
	"\x06models\x18\x01 \x03(\v2\r.tts.TTSModelR\x06models\"P\n" +
	"\bTTSModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x1f\n" +
	"\tTextChunk\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\v\n" +
	"\tEndOfText\"\x94\x01\n" +
	"\x10TtsClientMessage\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x15.tts.TtsSessionConfigH\x00R\x06config\x12$\n" +
	"\x04text\x18\x02 \x01(\v2\x0e.tts.TextChunkH\x00R\x04text\x12\"\n" +
	"\x03end\x18\x03 \x01(\v2\x0e.tts.EndOfTextH\x00R\x03endB\x05\n" +
	"\x03msg\"M\n" +
	"\x0fTtsSessionReady\x12\x19\n" +
	"\bvoice_id\x18\x01 \x01(\tR\avoiceId\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\rR\n" +
	"sampleRate\"\x9c\x01\n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\rR\n" +
	"sampleRate\x12!\n" +
	"\ftimestamp_ms\x18\x04 \x01(\x04R\vtimestampMs\x12\x1e\n" +
	"\n" +
	"transcript\x18\x05 \x01(\tR\n" +
	"transcript\"i\n" +
	"\bTtsUsage\x12\x19\n" +
	"\baudio_ms\x18\x01 \x01(\x04R\aaudioMs\x12#\n" +
	"\rprocessing_ms\x18\x02 \x01(\x04R\fprocessingMs\x12\x1d\n" +
	"\n" +
	"text_chars\x18\x03 \x01(\x04R\ttextChars\"\xd1\x01\n" +
	"\aTtsDone\x12*\n" +
	"\x11audio_duration_ms\x18\x01 \x01(\x04R\x0faudioDurationMs\x124\n" +
	"\x16processing_duration_ms\x18\x02 \x01(\x04R\x14processingDurationMs\x12\x1f\n" +
	"\vtext_length\x18\x03 \x01(\x04R\n" +
	"textLength\x12#\n" +
	"\x05usage\x18\x04 \x01(\v2\r.tts.TtsUsageR\x05usage\x12\x1e\n" +
	"\n" +
	"transcript\x18\x05 \x01(\tR\n" +
	"transcript\"8\n" +
	"\bTtsError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\rR\x04code\"\xbb\x01\n" +
	"\x10TtsServerMessage\x12,\n" +
	"\x05ready\x18\x01 \x01(\v2\x14.tts.TtsSessionReadyH\x00R\x05ready\x12'\n" +
	"\x05audio\x18\x02 \x01(\v2\x0f.tts.AudioChunkH\x00R\x05audio\x12\"\n" +
	"\x04done\x18\x03 \x01(\v2\f.tts.TtsDoneH\x00R\x04done\x12%\n" +
	"\x05error\x18\x04 \x01(\v2\r.tts.TtsErrorH\x00R\x05errorB\x05\n" +
	"\x03msg2\xd7\x02\n" +
	"\x13TextToSpeechService\x12>\n" +
	"\n" +
	"Synthesize\x12\x15.tts.TtsClientMessage\x1a\x15.tts.TtsServerMessage(\x010\x01\x12=\n" +
	"\n" +
	"ListVoices\x12\x16.tts.ListVoicesRequest\x1a\x17.tts.ListVoicesResponse\x12=\n" +
	"\n" +
	"ListModels\x12\x16.tts.ListModelsRequest\x1a\x17.tts.ListModelsResponse\x12@\n" +
	"\vCreateVoice\x12\x17.tts.CreateVoiceRequest\x1a\x18.tts.CreateVoiceResponse\x12@\n" +
	"\vDeleteVoice\x12\x17.tts.DeleteVoiceRequest\x1a\x18.tts.DeleteVoiceResponseB=Z;github.com/eleven-am/voice-backend/internal/synthesis/ttspbb\x06proto3"

var (
	file_proto_tts_proto_rawDescOnce sync.Once
	file_proto_tts_proto_rawDescData []byte
)

func file_proto_tts_proto_rawDescGZIP() []byte {
	file_proto_tts_proto_rawDescOnce.Do(func() {
		file_proto_tts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tts_proto_rawDesc), len(file_proto_tts_proto_rawDesc)))
	})
	return file_proto_tts_proto_rawDescData
}

var file_proto_tts_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_tts_proto_goTypes = []any{
	(*TtsSessionConfig)(nil),    // 0: tts.TtsSessionConfig
	(*ListVoicesRequest)(nil),   // 1: tts.ListVoicesRequest
	(*ListVoicesResponse)(nil),  // 2: tts.ListVoicesResponse
	(*Voice)(nil),               // 3: tts.Voice
	(*CreateVoiceRequest)(nil),  // 4: tts.CreateVoiceRequest
	(*CreateVoiceResponse)(nil), // 5: tts.CreateVoiceResponse
	(*DeleteVoiceRequest)(nil),  // 6: tts.DeleteVoiceRequest
	(*DeleteVoiceResponse)(nil), // 7: tts.DeleteVoiceResponse
	(*ListModelsRequest)(nil),   // 8: tts.ListModelsRequest
	(*ListModelsResponse)(nil),  // 9: tts.ListModelsResponse
	(*TTSModel)(nil),            // 10: tts.TTSModel
	(*TextChunk)(nil),           // 11: tts.TextChunk
	(*EndOfText)(nil),           // 12: tts.EndOfText
	(*TtsClientMessage)(nil),    // 13: tts.TtsClientMessage
	(*TtsSessionReady)(nil),     // 14: tts.TtsSessionReady
	(*AudioChunk)(nil),          // 15: tts.AudioChunk
	(*TtsUsage)(nil),            // 16: tts.TtsUsage
	(*TtsDone)(nil),             // 17: tts.TtsDone
	(*TtsError)(nil),            // 18: tts.TtsError
	(*TtsServerMessage)(nil),    // 19: tts.TtsServerMessage
}
var file_proto_tts_proto_depIdxs = []int32{
	3,  // 0: tts.ListVoicesResponse.voices:type_name -> tts.Voice
	3,  // 1: tts.CreateVoiceResponse.voice:type_name -> tts.Voice
	10, // 2: tts.ListModelsResponse.models:type_name -> tts.TTSModel
	0,  // 3: tts.TtsClientMessage.config:type_name -> tts.TtsSessionConfig
	11, // 4: tts.TtsClientMessage.text:type_name -> tts.TextChunk
	12, // 5: tts.TtsClientMessage.end:type_name -> tts.EndOfText
	16, // 6: tts.TtsDone.usage:type_name -> tts.TtsUsage
	14, // 7: tts.TtsServerMessage.ready:type_name -> tts.TtsSessionReady
	15, // 8: tts.TtsServerMessage.audio:type_name -> tts.AudioChunk
	17, // 9: tts.TtsServerMessage.done:type_name -> tts.TtsDone
	18, // 10: tts.TtsServerMessage.error:type_name -> tts.TtsError
	13, // 11: tts.TextToSpeechService.Synthesize:input_type -> tts.TtsClientMessage
	1,  // 12: tts.TextToSpeechService.ListVoices:input_type -> tts.ListVoicesRequest
	8,  // 13: tts.TextToSpeechService.ListModels:input_type -> tts.ListModelsRequest
	4,  // 14: tts.TextToSpeechService.CreateVoice:input_type -> tts.CreateVoiceRequest
	6,  // 15: tts.TextToSpeechService.DeleteVoice:input_type -> tts.DeleteVoiceRequest
	19, // 16: tts.TextToSpeechService.Synthesize:output_type -> tts.TtsServerMessage
	2,  // 17: tts.TextToSpeechService.ListVoices:output_type -> tts.ListVoicesResponse
	9,  // 18: tts.TextToSpeechService.ListModels:output_type -> tts.ListModelsResponse
	5,  // 19: tts.TextToSpeechService.CreateVoice:output_type -> tts.CreateVoiceResponse
	7,  // 20: tts.TextToSpeechService.DeleteVoice:output_type -> tts.DeleteVoiceResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_tts_proto_init() }
func file_proto_tts_proto_init() {
	if File_proto_tts_proto != nil {
		return
	}
	file_proto_tts_proto_msgTypes[13].OneofWrappers = []any{
		(*TtsClientMessage_Config)(nil),
		(*TtsClientMessage_Text)(nil),
		(*TtsClientMessage_End)(nil),
	}
	file_proto_tts_proto_msgTypes[19].OneofWrappers = []any{
		(*TtsServerMessage_Ready)(nil),
		(*TtsServerMessage_Audio)(nil),
		(*TtsServerMessage_Done)(nil),
		(*TtsServerMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tts_proto_rawDesc), len(file_proto_tts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tts_proto_goTypes,
		DependencyIndexes: file_proto_tts_proto_depIdxs,
		MessageInfos:      file_proto_tts_proto_msgTypes,
	}.Build()
	File_proto_tts_proto = out.File
	file_proto_tts_proto_goTypes = nil
	file_proto_tts_proto_depIdxs = nil
}
