// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: voice/gateway/v1/gateway.proto

package gatewaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED       ErrorCode = 0
	ErrorCode_ERROR_CODE_AGENT_UNAVAILABLE ErrorCode = 1
	ErrorCode_ERROR_CODE_AGENT_TIMEOUT     ErrorCode = 2
	ErrorCode_ERROR_CODE_INVALID_REQUEST   ErrorCode = 3
	ErrorCode_ERROR_CODE_INTERNAL          ErrorCode = 4
	ErrorCode_ERROR_CODE_UNAUTHORIZED      ErrorCode = 5
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_AGENT_UNAVAILABLE",
		2: "ERROR_CODE_AGENT_TIMEOUT",
		3: "ERROR_CODE_INVALID_REQUEST",
		4: "ERROR_CODE_INTERNAL",
		5: "ERROR_CODE_UNAUTHORIZED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":       0,
		"ERROR_CODE_AGENT_UNAVAILABLE": 1,
		"ERROR_CODE_AGENT_TIMEOUT":     2,
		"ERROR_CODE_INVALID_REQUEST":   3,
		"ERROR_CODE_INTERNAL":          4,
		"ERROR_CODE_UNAUTHORIZED":      5,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_voice_gateway_v1_gateway_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_voice_gateway_v1_gateway_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_voice_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

type ClientMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata  map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_SessionStart
	//	*ClientMessage_Utterance
	//	*ClientMessage_SessionEnd
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_voice_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ClientMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ClientMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetSessionStart() *SessionStart {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_SessionStart); ok {
			return x.SessionStart
		}
	}
	return nil
}

func (x *ClientMessage) GetUtterance() *Utterance {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Utterance); ok {
			return x.Utterance
		}
	}
	return nil
}

func (x *ClientMessage) GetSessionEnd() *SessionEnd {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_SessionEnd); ok {
			return x.SessionEnd
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_SessionStart struct {
	SessionStart *SessionStart `protobuf:"bytes,4,opt,name=session_start,json=sessionStart,proto3,oneof"`
}

type ClientMessage_Utterance struct {
	Utterance *Utterance `protobuf:"bytes,5,opt,name=utterance,proto3,oneof"`
}

type ClientMessage_SessionEnd struct {
	SessionEnd *SessionEnd `protobuf:"bytes,6,opt,name=session_end,json=sessionEnd,proto3,oneof"`
}

func (*ClientMessage_SessionStart) isClientMessage_Payload() {}

func (*ClientMessage_Utterance) isClientMessage_Payload() {}

func (*ClientMessage_SessionEnd) isClientMessage_Payload() {}

type SessionStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionStart) Reset() {
	*x = SessionStart{}
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStart) ProtoMessage() {}

func (x *SessionStart) ProtoReflect() protoreflect.Message {
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStart.ProtoReflect.Descriptor instead.
func (*SessionStart) Descriptor() ([]byte, []int) {
	return file_voice_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *SessionStart) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionStart) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type Utterance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	IsFinal       bool                   `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Utterance) Reset() {
	*x = Utterance{}
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Utterance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Utterance) ProtoMessage() {}

func (x *Utterance) ProtoReflect() protoreflect.Message {
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Utterance.ProtoReflect.Descriptor instead.
func (*Utterance) Descriptor() ([]byte, []int) {
	return file_voice_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *Utterance) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Utterance) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *Utterance) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Utterance) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SessionEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionEnd) Reset() {
	*x = SessionEnd{}
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionEnd) ProtoMessage() {}

func (x *SessionEnd) ProtoReflect() protoreflect.Message {
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionEnd.ProtoReflect.Descriptor instead.
func (*SessionEnd) Descriptor() ([]byte, []int) {
	return file_voice_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

type ServerMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata  map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_SessionConfig
	//	*ServerMessage_Response
	//	*ServerMessage_AgentStatus
	//	*ServerMessage_Error
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_voice_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ServerMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServerMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ServerMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetSessionConfig() *SessionConfig {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_SessionConfig); ok {
			return x.SessionConfig
		}
	}
	return nil
}

func (x *ServerMessage) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *ServerMessage) GetAgentStatus() *AgentStatusUpdate {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_AgentStatus); ok {
			return x.AgentStatus
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_SessionConfig struct {
	SessionConfig *SessionConfig `protobuf:"bytes,4,opt,name=session_config,json=sessionConfig,proto3,oneof"`
}

type ServerMessage_Response struct {
	Response *Response `protobuf:"bytes,5,opt,name=response,proto3,oneof"`
}

type ServerMessage_AgentStatus struct {
	AgentStatus *AgentStatusUpdate `protobuf:"bytes,6,opt,name=agent_status,json=agentStatus,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *Error `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

func (*ServerMessage_SessionConfig) isServerMessage_Payload() {}

func (*ServerMessage_Response) isServerMessage_Payload() {}

func (*ServerMessage_AgentStatus) isServerMessage_Payload() {}

func (*ServerMessage_Error) isServerMessage_Payload() {}

type SessionConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionConfig) Reset() {
	*x = SessionConfig{}
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionConfig) ProtoMessage() {}

func (x *SessionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionConfig.ProtoReflect.Descriptor instead.
func (*SessionConfig) Descriptor() ([]byte, []int) {
	return file_voice_gateway_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *SessionConfig) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Online        bool                   `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
	Capabilities  []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_voice_gateway_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Agent) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *Agent) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	FromAgent     string                 `protobuf:"bytes,2,opt,name=from_agent,json=fromAgent,proto3" json:"from_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_voice_gateway_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *Response) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Response) GetFromAgent() string {
	if x != nil {
		return x.FromAgent
	}
	return ""
}

type AgentStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Online        bool                   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStatusUpdate) Reset() {
	*x = AgentStatusUpdate{}
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusUpdate) ProtoMessage() {}

func (x *AgentStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStatusUpdate.ProtoReflect.Descriptor instead.
func (*AgentStatusUpdate) Descriptor() ([]byte, []int) {
	return file_voice_gateway_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *AgentStatusUpdate) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentStatusUpdate) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=voice.gateway.v1.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_voice_gateway_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_voice_gateway_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_voice_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_voice_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1evoice/gateway/v1/gateway.proto\x12\x10voice.gateway.v1\"\xa4\x03\n" +
	"\rClientMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12I\n" +
	"\bmetadata\x18\x03 \x03(\v2-.voice.gateway.v1.ClientMessage.MetadataEntryR\bmetadata\x12E\n" +
	"\rsession_start\x18\x04 \x01(\v2\x1e.voice.gateway.v1.SessionStartH\x00R\fsessionStart\x12;\n" +
	"\tutterance\x18\x05 \x01(\v2\x1b.voice.gateway.v1.UtteranceH\x00R\tutterance\x12?\n" +
	"\vsession_end\x18\x06 \x01(\v2\x1c.voice.gateway.v1.SessionEndH\x00R\n" +
	"sessionEnd\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\apayload\"@\n" +
	"\fSessionStart\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\"t\n" +
	"\tUtterance\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"\f\n" +
	"\n" +
	"SessionEnd\"\xde\x03\n" +
	"\rServerMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12I\n" +
	"\bmetadata\x18\x03 \x03(\v2-.voice.gateway.v1.ServerMessage.MetadataEntryR\bmetadata\x12H\n" +
	"\x0esession_config\x18\x04 \x01(\v2\x1f.voice.gateway.v1.SessionConfigH\x00R\rsessionConfig\x128\n" +
	"\bresponse\x18\x05 \x01(\v2\x1a.voice.gateway.v1.ResponseH\x00R\bresponse\x12H\n" +
	"\fagent_status\x18\x06 \x01(\v2#.voice.gateway.v1.AgentStatusUpdateH\x00R\vagentStatus\x12/\n" +
	"\x05error\x18\a \x01(\v2\x17.voice.gateway.v1.ErrorH\x00R\x05error\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\apayload\"@\n" +
	"\rSessionConfig\x12/\n" +
	"\x06agents\x18\x01 \x03(\v2\x17.voice.gateway.v1.AgentR\x06agents\"\x89\x01\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06online\x18\x04 \x01(\bR\x06online\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\"=\n" +
	"\bResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"from_agent\x18\x02 \x01(\tR\tfromAgent\"F\n" +
	"\x11AgentStatusUpdate\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06online\x18\x02 \x01(\bR\x06online\"\xce\x01\n" +
	"\x05Error\x12/\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1b.voice.gateway.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\adetails\x18\x03 \x03(\v2$.voice.gateway.v1.Error.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xbd\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cERROR_CODE_AGENT_UNAVAILABLE\x10\x01\x12\x1c\n" +
	"\x18ERROR_CODE_AGENT_TIMEOUT\x10\x02\x12\x1e\n" +
	"\x1aERROR_CODE_INVALID_REQUEST\x10\x03\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\x04\x12\x1b\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\x052_\n" +
	"\fVoiceGateway\x12O\n" +
	"\aSession\x12\x1f.voice.gateway.v1.ClientMessage\x1a\x1f.voice.gateway.v1.ServerMessage(\x010\x01BEZCgithub.com/eleven-am/voice-backend/internal/gateway/proto;gatewaypbb\x06proto3"

var (
	file_voice_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_voice_gateway_v1_gateway_proto_rawDescData []byte
)

func file_voice_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_voice_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_voice_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_voice_gateway_v1_gateway_proto_rawDesc), len(file_voice_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_voice_gateway_v1_gateway_proto_rawDescData
}

var file_voice_gateway_v1_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_voice_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_voice_gateway_v1_gateway_proto_goTypes = []any{
	(ErrorCode)(0),            // 0: voice.gateway.v1.ErrorCode
	(*ClientMessage)(nil),     // 1: voice.gateway.v1.ClientMessage
	(*SessionStart)(nil),      // 2: voice.gateway.v1.SessionStart
	(*Utterance)(nil),         // 3: voice.gateway.v1.Utterance
	(*SessionEnd)(nil),        // 4: voice.gateway.v1.SessionEnd
	(*ServerMessage)(nil),     // 5: voice.gateway.v1.ServerMessage
	(*SessionConfig)(nil),     // 6: voice.gateway.v1.SessionConfig
	(*Agent)(nil),             // 7: voice.gateway.v1.Agent
	(*Response)(nil),          // 8: voice.gateway.v1.Response
	(*AgentStatusUpdate)(nil), // 9: voice.gateway.v1.AgentStatusUpdate
	(*Error)(nil),             // 10: voice.gateway.v1.Error
	nil,                       // 11: voice.gateway.v1.ClientMessage.MetadataEntry
	nil,                       // 12: voice.gateway.v1.ServerMessage.MetadataEntry
	nil,                       // 13: voice.gateway.v1.Error.DetailsEntry
}
var file_voice_gateway_v1_gateway_proto_depIdxs = []int32{
	11, // 0: voice.gateway.v1.ClientMessage.metadata:type_name -> voice.gateway.v1.ClientMessage.MetadataEntry
	2,  // 1: voice.gateway.v1.ClientMessage.session_start:type_name -> voice.gateway.v1.SessionStart
	3,  // 2: voice.gateway.v1.ClientMessage.utterance:type_name -> voice.gateway.v1.Utterance
	4,  // 3: voice.gateway.v1.ClientMessage.session_end:type_name -> voice.gateway.v1.SessionEnd
	12, // 4: voice.gateway.v1.ServerMessage.metadata:type_name -> voice.gateway.v1.ServerMessage.MetadataEntry
	6,  // 5: voice.gateway.v1.ServerMessage.session_config:type_name -> voice.gateway.v1.SessionConfig
	8,  // 6: voice.gateway.v1.ServerMessage.response:type_name -> voice.gateway.v1.Response
	9,  // 7: voice.gateway.v1.ServerMessage.agent_status:type_name -> voice.gateway.v1.AgentStatusUpdate
	10, // 8: voice.gateway.v1.ServerMessage.error:type_name -> voice.gateway.v1.Error
	7,  // 9: voice.gateway.v1.SessionConfig.agents:type_name -> voice.gateway.v1.Agent
	0,  // 10: voice.gateway.v1.Error.code:type_name -> voice.gateway.v1.ErrorCode
	13, // 11: voice.gateway.v1.Error.details:type_name -> voice.gateway.v1.Error.DetailsEntry
	1,  // 12: voice.gateway.v1.VoiceGateway.Session:input_type -> voice.gateway.v1.ClientMessage
	5,  // 13: voice.gateway.v1.VoiceGateway.Session:output_type -> voice.gateway.v1.ServerMessage
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_voice_gateway_v1_gateway_proto_init() }
func file_voice_gateway_v1_gateway_proto_init() {
	if File_voice_gateway_v1_gateway_proto != nil {
		return
	}
	file_voice_gateway_v1_gateway_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_SessionStart)(nil),
		(*ClientMessage_Utterance)(nil),
		(*ClientMessage_SessionEnd)(nil),
	}
	file_voice_gateway_v1_gateway_proto_msgTypes[4].OneofWrappers = []any{
		(*ServerMessage_SessionConfig)(nil),
		(*ServerMessage_Response)(nil),
		(*ServerMessage_AgentStatus)(nil),
		(*ServerMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_voice_gateway_v1_gateway_proto_rawDesc), len(file_voice_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_voice_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_voice_gateway_v1_gateway_proto_depIdxs,
		EnumInfos:         file_voice_gateway_v1_gateway_proto_enumTypes,
		MessageInfos:      file_voice_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_voice_gateway_v1_gateway_proto = out.File
	file_voice_gateway_v1_gateway_proto_goTypes = nil
	file_voice_gateway_v1_gateway_proto_depIdxs = nil
}
