// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: voice/gateway/v1/gateway.proto

package gatewaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VoiceGateway_Session_FullMethodName = "/voice.gateway.v1.VoiceGateway/Session"
)

// VoiceGatewayClient is the client API for VoiceGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoiceGatewayClient interface {
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error)
}

type voiceGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewVoiceGatewayClient(cc grpc.ClientConnInterface) VoiceGatewayClient {
	return &voiceGatewayClient{cc}
}

func (c *voiceGatewayClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VoiceGateway_ServiceDesc.Streams[0], VoiceGateway_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoiceGateway_SessionClient = grpc.BidiStreamingClient[ClientMessage, ServerMessage]

// VoiceGatewayServer is the server API for VoiceGateway service.
// All implementations must embed UnimplementedVoiceGatewayServer
// for forward compatibility.
type VoiceGatewayServer interface {
	Session(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error
	mustEmbedUnimplementedVoiceGatewayServer()
}

// UnimplementedVoiceGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoiceGatewayServer struct{}

func (UnimplementedVoiceGatewayServer) Session(grpc.BidiStreamingServer[ClientMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedVoiceGatewayServer) mustEmbedUnimplementedVoiceGatewayServer() {}
func (UnimplementedVoiceGatewayServer) testEmbeddedByValue()                      {}

// UnsafeVoiceGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoiceGatewayServer will
// result in compilation errors.
type UnsafeVoiceGatewayServer interface {
	mustEmbedUnimplementedVoiceGatewayServer()
}

func RegisterVoiceGatewayServer(s grpc.ServiceRegistrar, srv VoiceGatewayServer) {
	// If the following call panics, it indicates UnimplementedVoiceGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VoiceGateway_ServiceDesc, srv)
}

func _VoiceGateway_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VoiceGatewayServer).Session(&grpc.GenericServerStream[ClientMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VoiceGateway_SessionServer = grpc.BidiStreamingServer[ClientMessage, ServerMessage]

// VoiceGateway_ServiceDesc is the grpc.ServiceDesc for VoiceGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VoiceGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voice.gateway.v1.VoiceGateway",
	HandlerType: (*VoiceGatewayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _VoiceGateway_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "voice/gateway/v1/gateway.proto",
}
