# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import pb2 as tts__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TextToSpeechServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Synthesize = channel.stream_stream(
                '/tts.TextToSpeechService/Synthesize',
                request_serializer=tts__pb2.TtsClientMessage.SerializeToString,
                response_deserializer=tts__pb2.TtsServerMessage.FromString,
                _registered_method=True)
        self.ListVoices = channel.unary_unary(
                '/tts.TextToSpeechService/ListVoices',
                request_serializer=tts__pb2.ListVoicesRequest.SerializeToString,
                response_deserializer=tts__pb2.ListVoicesResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/tts.TextToSpeechService/ListModels',
                request_serializer=tts__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=tts__pb2.ListModelsResponse.FromString,
                _registered_method=True)


class TextToSpeechServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Synthesize(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVoices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextToSpeechServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Synthesize': grpc.stream_stream_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=tts__pb2.TtsClientMessage.FromString,
                    response_serializer=tts__pb2.TtsServerMessage.SerializeToString,
            ),
            'ListVoices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVoices,
                    request_deserializer=tts__pb2.ListVoicesRequest.FromString,
                    response_serializer=tts__pb2.ListVoicesResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=tts__pb2.ListModelsRequest.FromString,
                    response_serializer=tts__pb2.ListModelsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tts.TextToSpeechService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tts.TextToSpeechService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TextToSpeechService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Synthesize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/tts.TextToSpeechService/Synthesize',
            tts__pb2.TtsClientMessage.SerializeToString,
            tts__pb2.TtsServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts.TextToSpeechService/ListVoices',
            tts__pb2.ListVoicesRequest.SerializeToString,
            tts__pb2.ListVoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tts.TextToSpeechService/ListModels',
            tts__pb2.ListModelsRequest.SerializeToString,
            tts__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
